In [2]:
import numpy as np

## happy indexing

In [6]:
#random z.b. 165 ortskoordinaten generieren
a = np.random.rand(165,3)
print(f'Shape: {a.shape}')
a[:4]

Shape: (165, 3)


array([[0.07440807, 0.04122917, 0.51645126],
       [0.75154144, 0.87487479, 0.37576749],
       [0.42798919, 0.62860552, 0.83137982],
       [0.70952365, 0.99451719, 0.09699096]])

In [9]:
#nur erste spalte (quasi x koordinaten z.b.)
x_coord = a[:,0]
len(x_coord)

165

In [12]:
#auch
xy_bis3 = a[:3, :2]
xy_bis3

array([[0.07440807, 0.04122917],
       [0.75154144, 0.87487479],
       [0.42798919, 0.62860552]])

## np.all, np.any

In [14]:
specific_position = a[-1]
mask = np.all((a == specific_position), axis=1)
#alle 3 koordinaten müssen gleich sein -> np.all mit axis=1 hier zeilen, axis=0 wären spalten

mask

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [34]:
mask1 = a == specific_position
print(f'step1:\n {mask1[-3:]}\n')

mask1[-1,2] = False
print(f'step2:\n {mask1[-3:]}\n')

helper = np.all(mask1, axis=1) #schaut, ob in jeder Zeile alle gleich sind -> nur mehr array shape (165)
print(f'step3:\n {helper[-4:]}\n')

any = np.any(helper)#schaut, obs irgendwo im array einen True-Wert gibt
print(f'step3:\nany? {any}\n')


step1:
 [[False False False]
 [False False False]
 [ True  True  True]]

step2:
 [[False False False]
 [False False False]
 [ True  True False]]

step3:
 [False False False False]

step3:
any? False



### np.where

In [13]:
#np.where(condition, x, y)
b = np.arange(2,10)
print(f'b= {b}')
#...entweder nur condition angeben, dann spuckt es array mit INDIZES der zutreffenden elementen aus
print(f'np.where: {np.where(b<5)}')

b= [2 3 4 5 6 7 8 9]
np.where: (array([0, 1, 2], dtype=int64),)


In [11]:
#..oder x, y [beide oder nix!] angeben.. ähnlich WENN-DANN funktion.. -> spuckt ELEMENTE aus
#'dort wo condition zutrifft mach x mit den elementen, dort wo nicht zutrifft mach y'

np.where(b%2==0, b, b*10)

array([ 2, 30,  4, 50,  6, 70,  8, 90])